#
# blacklist.conf
# ==============
#
# In this file the blacklist for the automatic fixes search is
# configured. There are two ways to blacklist potential fixes:
#
#	1) Put a source code path on one line in this file. If a patch
#	   touches only source code paths that are blacklisted in this
#	   file, it will be automatically blacklisted too.
#
#	2) Put a full git commit-id on one line in this file. The
#	   commit-id needs to be a 40 character-long hex string.
#
# As noted above, only one path or commit-id per line is allowed.
# Everything behind a '#' character is considered a comment and ignored.
#
# This file is parsed by the git-suse tool.

# Blacklisted Paths
# -----------------

# Blacklisted Commits
# -------------------

505f394fa239cecb76d916aa858f87ed7ea7fde4	# HID: inapplicable
93a2207c254ca102ebbdae47b00f19bbfbfa7ecd	# HID: non-existing code in this branch
2f09707d0c972120bf794cfe0f0c67e2c2ddb252	# sch_sfb: irrelevant with this kernel
6d2289f3faa71dcc5bba15c7aeba4f31c185b6df	# bsc#1209549 CVE-2023-28772
