# Kernel configuration file selection.
# See the arch-symbols script for a list of symbols defined.
# -syms excludes a flavor from the kernel-syms package (vanilla is excluded
# automatically).

#
# IMPORTANT: the subdirectory names map to cpuarch
#            kernel-binary and kernel-source rely on this
#

+i386		i386/default
+i386		i386/pae
+i386 -syms	i386/debug
+i386		i386/xen
+i386 -syms	i386/ec2
+i386 		i386/vanilla
+i386		i386/trace

+x86_64		x86_64/default
+x86_64		x86_64/xen
+x86_64	-syms	x86_64/ec2
+x86_64	-syms	x86_64/debug
+x86_64		x86_64/vanilla
+x86_64		x86_64/trace
