#!/bin/sh

enable_x() {
	local enable=true
	while [ $# -gt 0 ] ; do
		{ [ "$1" = "-q" ] || [ "$1" = "--quiet" ] ; } && enable=false
		shift
	done
	$enable && set -x
	}

enable_x "$@"

testdir=$(dirname "$(readlink -f "$0")")

result=0
for release in \
	sle_12_sp5 \
	sle_15_sp4 \
	sle_15_sp7 \
	16.0 \
	opensuse_factory \
	; do
	echo "Running container for $release..."
	container=$(podman run --rm -d -i -v ./scripts:/scripts:ro -w /scripts/python registry.opensuse.org/kernel/tools/images/$release/kernel-scripts:latest sleep 1h)
	ret=$?
	podman exec $container git config --global user.email "you@example.com"
	podman exec $container git config --global user.name "Your Name"
	if ! [ $ret -eq 0 ] ; then
		result=$ret
		continue
	fi
	echo "Running tests in $release:"
	podman exec $container python3 -m unittest discover -v "$@"
	ret=$?
	podman stop $container
	if ! [ $ret -eq 0 ] ; then
		result=$ret
		continue
	fi
done
exit $result
